import = [
  "~/.config/alacritty/cursor.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/window.toml",
  "~/.config/alacritty/selection.toml",
  "~/.config/alacritty/themes/solarized_dark.toml",
]
